services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      # - ./data/migrations:/docker-entrypoint-initdb.d

  pgadmin:
    image: elestio/pgadmin
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db

  # client:
  #   build:
  #     context: ./client
  #   container_name: client
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=development
  #     - WATCHPACK_POLLING=true
  #   volumes:
  #     - ./client:/app

  admin: 
    image: node:23-alpine3.20
    container_name: admin
    ports:
      - "3001:3000"
    environment:
      NODE_ENV: development
      WATCHPACK_POLLING: true
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - ./admin:/app
    command: sh -c "cd /app && npm install && npx prisma migrate dev --name init && npm run dev"